services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
  
  worker:
    build: .
    command: celery -A app.core.celery.celery_app worker -Q main-queue --loglevel=info
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A app.core.celery.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
